name: dcd_flut_local_file
description: This repository contains a Flutter mobile application developed for
  learning fundamental flutter development based on Dicoding Class. The
  application focuses on creating simple read and write to file that stored on
  internal storage Android and iOS.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
